---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: pyspark-pi
spec:
  sparkConf:
    "spark.task.maxFailures": "3"        # retries per task (default 4)
    "spark.stage.maxConsecutiveAttempts": "8"  # stage retry limit
  sparkImage:
    productVersion: 3.5.6
  mode: cluster
  mainApplicationFile: local:///stackable/spark/examples/src/main/python/pi.py
  job:
    podOverrides:
      spec:
        template:
          spec:
            restartPolicy: OnFailure
  executor:
    replicas: 1
